from django.urls import path
from .views import (
    AdminLoginView,
    RolLoginView,
    CrearCompetenciaView,
    EliminarCompetenciaView,
    ListaCompetenciasView,
    CrearDeportistasView,
    EditarDeportistaView,
    EliminarDeportistaView,
    EliminarJuezView,
    EliminarOrganizadorView,
    CrearJuezView,
    CrearOrganizadorView,
    BuscarJuezView,
    BuscarOrganizadorView,
    BuscarDeportistaView,
    RegistrarPuntuacionIndividualView,   
    ListaOrganizadoresView,
    ListaJuecesView,
    BuscarAdministradorPorCredencialView,
    BuscarJuezPorCredencialView,
    BuscarOrganizadorPorCredencialView,
    ListarDeportistasView,
    VerCredencialJuezView,
    VerCredencialOrganizadorView,
    ActualizarSaltosView,
    ListarYActualizarRankingView,
    ListaAdministradoresView,
    VerCredencialAdministradorView,
    EliminarAdministradorView,
    CrearAdministradorView,
)

urlpatterns = [
    path('admin_login/', AdminLoginView.as_view(), name='admin_login'),
    path('rol_login/', RolLoginView.as_view(), name='rol_login'),

    path('crear_competencia/', CrearCompetenciaView.as_view(), name='crear_competencia'),
    path('eliminar_competencia/<str:competencia_id>/', EliminarCompetenciaView.as_view(), name='eliminar_competencia'),
    path('lista_competencias/', ListaCompetenciasView.as_view(), name='lista_competencias'),

    path('registrar/puntuacion_individual/', RegistrarPuntuacionIndividualView.as_view(), name='registrar_puntuacion'),

    path('crear_deportistas/', CrearDeportistasView.as_view(), name='crear_deportistas'),
    path('editar_deportista/<str:deportista_id>/', EditarDeportistaView.as_view(), name='editar_deportista'),
    path('eliminar_deportista/<str:deportista_id>/', EliminarDeportistaView.as_view(), name='eliminar_deportista'),
    path('eliminar_juez/<str:nombre>/', EliminarJuezView.as_view(), name='eliminar_juez'),
    path('eliminar_organizador/<str:nombre>/', EliminarOrganizadorView.as_view(), name='eliminar_organizador'),
    path('crear_juez/', CrearJuezView.as_view(), name='crear_juez'),
    path('crear_organizador/', CrearOrganizadorView.as_view(), name='crear_organizador'),
    path('buscar_juez/', BuscarJuezView.as_view(), name='buscar_juez'),
    path('buscar_organizador/', BuscarOrganizadorView.as_view(), name='buscar_organizador'),
    path("buscar_deportista/<str:nombre>/", BuscarDeportistaView.as_view(), name="buscar_deportista"),
    path("listar_organizadores/", ListaOrganizadoresView.as_view(), name="listar_organizadores"),
    path("listar_jueces/", ListaJuecesView.as_view(), name="listar_jueces"),
    path("buscar_administrador_por_credencial/", BuscarAdministradorPorCredencialView.as_view(), name="buscar_juez_por_credencial"),
    path("buscar_juez_por_credencial/", BuscarJuezPorCredencialView.as_view(), name="buscar_juez_por_credencial"),
    path("buscar_organizador_por_credencial/", BuscarOrganizadorPorCredencialView.as_view(), name="buscar_organizador_por_credencial"),
    path("listar_deportistas/", ListarDeportistasView.as_view(), name="buscar_deportista"),
    path("ver_credencial_juez/<str:nombre>/", VerCredencialJuezView.as_view(), name="ver_credencial_juez"),
    path("ver_credencial_organizador/<str:nombre>/", VerCredencialOrganizadorView.as_view(), name="ver_credencial_organizado"),
    path('actualizar_saltos/<str:nombre>/', ActualizarSaltosView.as_view(), name='actualizar_saltos'),
    path('listar_y_actualizar_rankin/', ListarYActualizarRankingView.as_view(), name='listar_y_actualizar_ranking'),
    path('listar_administradores/', ListaAdministradoresView.as_view(), name='listar_administradores'),
    path('ver_credencial_administrador/<str:nombre>/', VerCredencialAdministradorView.as_view(), name='ver_credencial_administrador'),
    path('eliminar_administrador/<str:nombre>/', EliminarAdministradorView.as_view(), name='eliminar_administrador'),
    path('crear_administrador/', CrearAdministradorView.as_view(), name='crear_administrador'),
    path('buscar_admin_por_nombre/<str:nombre>/', BuscarAdminPorNombreView.as_view(), name='buscar_admin_por_nombre')
]

